export const GET_NOMINATED_MOVIES = "GET_NOMINATED_MOVIES";
export const GET_NOMINATED_MOVIES_SUCCESSFUL =
  "GET_NOMINATED_MOVIES_SUCCESSFUL";
export const GET_NOMINATED_MOVIES_FAILURE = "GET_NOMINATED_MOVIES_FAILURE";
