export const SEARCH_TERM_CHANGE = "SEARCH_TERM_CHANGE";
export const SEARCH_SUCCESSFUL = "SEARCH_SUCCESSFUL";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const NOMINATE_RESULT = "NOMINATE_RESULT";
export const NOMINATE_RESULT_SUCCESSFUL = "NOMINATE_RESULT_SUCCESSFUL";
export const NOMINATE_RESULT_FAILURE = "NOMINATE_RESULT_FAILURE";
